#!/bin/sh

/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/lenera.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/e-ustin.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/erarta.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/erarta.com -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/unitedwines.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/parustravel.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/4krasota.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/gigants.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/nsa.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/fontanka113.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/2para.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/umbrella.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/rossita-travel.com -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/archive.mk-1.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/auroracomp.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/polaris-spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/lskspb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/s-teffi.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/prommetcon.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/credit-bulgaria.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/davinci.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/aicipc.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/rybka.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/pmholding-v2.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/ellada.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/probike.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/e-ustin.com -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/fgtours.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/stewie.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/eastmarket.lenera.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/gekom.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/tdmey.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/kp-agro.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/new.portpc-design.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/1asx.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/ar.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/davinci-tours.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/gekom.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/mega-master.com -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/energouchet.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/lvk.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/sa-samal.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/teocom.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/clubred.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/new.pc-orbita.com -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/bars-hydraulic.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/tester3.lenera.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/avtomaster-spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/izumi.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/exportconsulting.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/rockmarket.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/azeri.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/azeri.ppd.spb.ru/ruslanimanov.msk.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/azeri.ppd.spb.ru/hrmaximum.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/btk.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/fdt-lazermed.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/alliance-credit.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/bemp.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/bronko.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/lans.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/prosto-credit.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/izumi-electronics.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/dreamjet.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl

/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/spylex.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/spylex.com -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/qforsa.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/qforsa.com -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/aer-tour.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/kvs.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/izumi-electronics.com -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/izumi-electronics.jp -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/wexler.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/hr.ppd.spb.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
/usr/local/www/awstats/tools/awstats_updateall.pl now -configdir=/www/tinkoff.ru -awstatsprog=/usr/local/www/awstats/cgi-bin/awstats.pl
